//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BoxNestGroup.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BoxNestGroup.Properties.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   無制限 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BOX_USER_DISK_UNLIMITED {
            get {
                return ResourceManager.GetString("BOX_USER_DISK_UNLIMITED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   制限なし に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BOX_USER_LIMIT_DISABELD {
            get {
                return ResourceManager.GetString("BOX_USER_LIMIT_DISABELD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   制限あり に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BOX_USER_LIMIT_ENABLED {
            get {
                return ResourceManager.GetString("BOX_USER_LIMIT_ENABLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   外部コラボレーション制限 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EXCEL_USER_COLABO {
            get {
                return ResourceManager.GetString("EXCEL_USER_COLABO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   グループ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EXCEL_USER_GROUP {
            get {
                return ResourceManager.GetString("EXCEL_USER_GROUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   メール に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EXCEL_USER_MAIL {
            get {
                return ResourceManager.GetString("EXCEL_USER_MAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   名前 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EXCEL_USER_NAME {
            get {
                return ResourceManager.GetString("EXCEL_USER_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ストレージ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EXCEL_USER_STORAGE {
            get {
                return ResourceManager.GetString("EXCEL_USER_STORAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   html/login.html に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FILE_NAME_LOGIN_HTML {
            get {
                return ResourceManager.GetString("FILE_NAME_LOGIN_HTML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [OFFLINE] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ID_NAME_OFFLINE {
            get {
                return ResourceManager.GetString("ID_NAME_OFFLINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   取得失敗 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LOGIN_FAIL {
            get {
                return ResourceManager.GetString("LOGIN_FAIL", resourceCulture);
            }
        }
    }
}
